Get http://localhost:3001/users?q=
###
POST http://localhost:3004/api/users
Content-Type: application/json

{
 "email"
: 
"m1axmadov@gmail.com",
"first_name"
: 
"Jack",
"info"
: 
"sfdghrstghrt",
"last_name"
: 
"Baratov",
"password"
: 
"Jahongir7A",
"phone"
: 
"998501015667",
"specialization"
: 
"dbgfsdttgb",
"type": "student",
"username": "san_mani_dardim55"
}
###
POST http://localhost:3001/users/verify
Content-Type: application/json

{
  "email":"johndoe123456@gmail.com",
  "password":"186837"
}
###
POST http://localhost:3001/users/forgot1
Content-Type: application/json

{
  "email":"m1axmadov@gmail.com"
}
###
POST http://localhost:3001/users/forgot2
Content-Type: application/json

{
  "email":"m1axmadov@gmail.com",
  "password":"Jahongir7A",
  "emailpassword":"976409"
}
###
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "username": "zuxi@gmail.com",
  "password": "zuxi"
}